FROM node:22-alpine

WORKDIR /app

# Instala dependências globais se necessário (ex: wget para healthcheck)
RUN apk add --no-cache wget

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
